spring:
  application:
    name: inquisitor-demo
  profiles:
    active: local
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
