spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
